#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

#rules
bspc rule -a Zathura state=tiled
bspc rule -a Firefox desktop=^9
bspc rule -a Thunderbird desktop=^8

/home/cmedlin/.config/lemonbar/input.sh | lemonbar
firefox
thunderbird
